name: dhanyacm
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: ""
url: http://dhanyacm.github.io/
permalink: /404.html
include: ["_pages"]
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:title/


