name: dhanyacm
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: ""
url: https://dhanyacm.com/
include: ["_pages"]
paginate: 5
permalink: /:title/
permalink: /404.html


