name: dhanyacm
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: ""
url: http://dhanyacm.github.io/
include: ["_pages"]
permalink: /:title/
permalink: /404.html
paginate: 5
paginate_path: "/blog/page:num/"
